jobs:

- job: check_formatting
  displayName: Check formatting (allow failure)
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        $HOME/.cargo/bin/rustup toolchain add nightly
      displayName: Install nightly Rust
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      nightly:
        rustup_toolchain: nightly
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        $HOME/.cargo/bin/rustup toolchain add nightly-x86_64-unknown-linux-musl
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
    # All platforms.
    - script: |
        rustc -Vv
        cargo -V
      displayName: Query rust and cargo versions
    - script: |
        uname -a
        /bin/bash --version
        timeout --version
      displayName: Check environment
    - script: git submodule update --init --recursive
      displayName: Update submodules
    - script: make
      displayName: Build
    - script: make tests
      displayName: Run tests
