jobs:

- job: check_formatting
  displayName: Check formatting
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        $HOME/.cargo/bin/rustup toolchain add nightly
        $HOME/.cargo/bin/rustup component add rustfmt
      displayName: Install nightly Rust
    - script: |
        $HOME/.cargo/bin/cargo fmt -- --check
      displayName: Run rustfmt

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      nightly:
        rustup_toolchain: nightly
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
    # All platforms.
    - script: |
        rustc -Vv
        cargo -V
      displayName: Query rust and cargo versions
    - script: make && make tests
      displayName: Build and run tests
