[package]
name = "systrace"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[workspace]
members= [".", "syscalls", "examples/echotool", "examples/none"]
default-members = [".", "syscalls", "examples/echotool", "examples/none"]

[[bin]]
name = "systrace"
path = "src/main.rs"

[dependencies]
libc = { version = "0.2", default-features = false }
nix = "0.13"
goblin = "0.0"
procfs = "0.4"
clap = "2.32"
combine = "3.6"
lazy_static = "1.2"
colored = "1.7"
chrono = "0.4"
log = "0.4"
fern = "0.5"

[build-dependencies]
cc = "1.0.28"
sysnum = { path = "sysnum" }
