[package]
name = "systrace"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[[bin]]
name = "systrace"
path = "src/main.rs"

[lib]
name = "det"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
libc = { version = "0.2", default-features = false }
nix = "0.12.0"

[build-dependencies]
cc = "1.0.28"
