[package]
name = "systrace"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[[bin]]
name = "systrace"
path = "src/main.rs"

[dependencies]
libc = { version = "0.2", default-features = false }
nix = "0.13"
goblin = "0.0"
procfs = "0.4"
clap = "2.32"

[build-dependencies]
cc = "1.0.28"
sysnr = { path = "sysnr" }
