[package]
name = "systrace"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[workspace]
members= [".", "syscalls", "tools_helper", "examples/echo", "examples/none", "examples/counter", "examples/det" ]
default-members = [".", "syscalls" ]

[lib]
name = "systrace"
path = "src/lib.rs"

[[bin]]
name = "systrace"
path = "src/main.rs"

[dependencies]
libc = { version = "0.2", default-features = false }
nix = "0.13"
goblin = "0.0"
procfs = "0.5"
clap = "2.32"
combine = "3.6"
lazy_static = "1.3"
colored = "1.7"
chrono = "0.4"
log = "0.4"
fern = "0.5"
tokio = "0.1"
hyper = "0.12"
hyperlocal = "0.6"
futures = "0.1"
serde_json = "1.0"

[build-dependencies]
cc = "1.0"
sysnum = { path = "sysnum" }
