[workspace]
members= ["reverie", "syscalls", "reverie-helper", "reverie-common", "reverie-preloader", "examples/none", "examples/echo", "examples/counter", "examples/det" ]
default-members = ["reverie", "syscalls", "reverie-common", "reverie-preloader" ]
