[package]
name = "echotool"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[lib]
name = "echotool"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]

[build-dependencies]
cc = "1.0.28"
sysnr = { path = "../../sysnr" }
