[package]
name = "echo"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[workspace]

[lib]
name = "echo"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
syscalls = { path = "../../syscalls" }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = [ "derive" ] }

[build-dependencies]
cc = "1.0"
