[package]
name = "reverie-syscalls"
version = "0.1.0"
authors = ["Baojun Wang <wangbj@gmail.com>"]
edition = "2018"

[lib]
name = "reverie_syscalls"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
reverie-sysnum = { path = "../reverie-sysnum" }
